spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

stripe:
  secret-key: pk_test_51NjqKaD9B53vbPRuLJC5jgngD3HeNJSR6fSsUV4UiWk5WN98iqNw8pyc8Md4z82jlZndKt28eOnuSWHRJsp609KK00WSf24PRo
  webhook-secret:  sk_test_51NjqKaD9B53vbPRuj0GEECHtDEOazZ7CqOuwVDW0tIoWq1yaH9HPnmcXmTCrhsPXovIntOFaA0DAKam8YqVidHqG00XsIeH4HI