spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  redis:
    host: localhost
    port: 6379
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
server:
  port: 8081
stripe:
  secret-key: sk_test_51RNZUmQPDJgVN9rq1ubvSJZdxIWbSuwmpMf9Xo975Cqrr1KVSwe5wKTMmNp0Nqfqb7DFx2wwEJs55vPGA19VepHc00yl72wxF0
  webhook-secret:

invoices:
  dir: target/invoices

app:
  capacity:
    orders:
      maxConcurrent: 4
      queueSize: 50

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
spring:
  zipkin:
    base-url: http://localhost:9411
  metrics:
    distribution:
      percentiles:
        order.simple: 0.95, 0.99
        order.optimized: 0.95, 0.99
      percentiles-histogram:
        order.simple: true
        order.optimized: true
